### PR TITLE
Add array snapshots feature

### PR DESCRIPTION
**Pull request by mmccorry**
Add SciDB snapshot roll-back feature to restore DB to previous state if a load fails.

- Take snapshot of SciDB arrays prior to data loading queries (using `versions()`)
- Wrap all load-related logic in a `tryCatch` block
- Restore to snapshot on error (iff any arrays have changed)

This logic has been added to
- All PUT/POST endpoints in REST server
- API-accessible load call in `revealsc`: `revealsc_post_expression_data_from_seurat_object_to_sample()`

### CODE REVIEW

**Comment by mmccorry** [comment]
Need to speed-up the snapshot query before merging this in.

First try providing the schema to the iquery calls.

If needs further performance improvements, use R to construct a long query of `versions()` for each array and joins them together so we have `max(version_id)` for each array name

**Comment by mmccorry** [comment]
@ksens 
I will test this branch and deploy likely before you are able to review.  Adding you as a reviewer so you may look this over later.

**Comment by mmccorry** [comment]
Current Python and R tests passing (except `restsc` and `revealsc` output comparisons, as expected):

Python tests:
```
-bash-4.2$ ./run_tests.sh -v
Connecting to REST API server at: http://scrnaseq-dev.rdcloud.bms.com:9009/api/v0
test010_GET_projects (__main__.RESTAPITests)
Test getting a list of all projects ... ok
test015_POST_project (__main__.RESTAPITests)
Test creating a project with no samples or tags ... ok
test017_POST_project (__main__.RESTAPITests)
Test creating a project with no samples and 1 tag ... ok
test020_POST_project (__main__.RESTAPITests)
Test creating a project with no samples and multiple tags ... ok
test025_GET_project (__main__.RESTAPITests)
Test retrieving a specific project that does NOT exist ... ok
test030_GET_project (__main__.RESTAPITests)
Test retrieving a specific project that should exist (from test20) ... ok
test040_PUT_project (__main__.RESTAPITests)
Test putting (updating) a project's tags ... ok
test045_POST_project (__main__.RESTAPITests)
Test adding samples to project and fail due to missing required fields ... ok
test046_POST_project (__main__.RESTAPITests)
Test adding samples without tags to project ... ok
test050_POST_project (__main__.RESTAPITests)
Test adding samples (sampleA, sampleB) with no expression data to a project (from test20) ... ok
test051_POST_project (__main__.RESTAPITests)
Test adding sample (sampleC) with expression data from local path to a project (from test20) ... ok
test052_POST_project (__main__.RESTAPITests)
Test adding duplicate sample to a project and fail ... ok
test053_POST_project (__main__.RESTAPITests)
Test adding sample (sampleD) with expression data from s3 path to a project (from test20) ... ok
test054_POST_project (__main__.RESTAPITests)
Test adding sample (sampleE) with expression data and no tags from s3 path to a project (from test20) ... ok
test055_GET_project (__main__.RESTAPITests)
Test getting a project that has 5 samples (from test20, test50, test51, test54) ... ok
test070_GET_sample (__main__.RESTAPITests)
Test getting a specific sample ... ok
test090_PUT_sample (__main__.RESTAPITests)
Test adding/updating tags on an existing sample ... ok
test100_POST_sample (__main__.RESTAPITests)
Test load cells & expression data for an existing sample (sampleA) from local path (from test50) ... ok
test101_POST_sample (__main__.RESTAPITests)
Test load cells & expression data for an existing sample (sampleB) from s3 path (from test50) ... ok
test110_GET_cell (__main__.RESTAPITests)
Test getting cells from a specific sample ... ok
test120_PUT_cell (__main__.RESTAPITests)
Test updating/adding tags on a cell or cells ... FAIL

======================================================================
FAIL: test120_PUT_cell (__main__.RESTAPITests)
Test updating/adding tags on a cell or cells
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/REST_API_Tests.py", line 587, in test120_PUT_cell
    self.fail("not yet implemented")
AssertionError: not yet implemented

----------------------------------------------------------------------
Ran 21 tests in 499.967s

FAILED (failures=1)
```

R tests:
```
══ Failed ══════════════════════════════════════════════════════════════════════
── 1. Failure: test010_GET_projects - Test getting a list of all projects (@test
identical(rest_projects, reveal_projects) isn't true.

── 2. Failure: test025_GET_project - Test retrieving a specific project that doe
identical(rest_project, reveal_project) isn't true.

── 3. Failure: test030_GET_project - Test retrieving a specific project that sho
identical(rest_project, reveal_project) isn't true.

── 4. Failure: test035_GET_project - Test retrieving a specific project that sho
identical(rest_project, reveal_project) isn't true.

── 5. Failure: test070_GET_sample - Test getting a specific sample (@test_reveal
`rest_sample` not equal to `reveal_sample`.
Component “tags_df”: Component “doid”: 'current' is not a factor
Component “tags_df”: Component “enrichment”: 'current' is not a factor
Component “tags_df”: Component “organism”: 'current' is not a factor
Component “tags_df”: Component “uberonid”: 'current' is not a factor

══ DONE ════════════════════════════════════════════════════════════════════════
```

So nothing existing has been broken.

Will now retest with the added REST server rollback test...

**Comment by mmccorry** [comment]
New python test added to test rollback on load fail at customer deployment.  With the above commit, all tests passing:
```
-bash-4.2$ ./run_tests.sh -v
Connecting to REST API server at: http://scrnaseq-dev.rdcloud.bms.com:9009/api/v0
test010_GET_projects (__main__.RESTAPITests)
Test getting a list of all projects ... ok
test015_POST_project (__main__.RESTAPITests)
Test creating a project with no samples or tags ... ok
test017_POST_project (__main__.RESTAPITests)
Test creating a project with no samples and 1 tag ... ok
test020_POST_project (__main__.RESTAPITests)
Test creating a project with no samples and multiple tags ... ok
test025_GET_project (__main__.RESTAPITests)
Test retrieving a specific project that does NOT exist ... ok
test030_GET_project (__main__.RESTAPITests)
Test retrieving a specific project that should exist (from test20) ... ok
test040_PUT_project (__main__.RESTAPITests)
Test putting (updating) a project's tags ... ok
test045_POST_project (__main__.RESTAPITests)
Test adding samples to project and fail due to missing required fields ... ok
test046_POST_project (__main__.RESTAPITests)
Test adding samples without tags to project ... ok
test050_POST_project (__main__.RESTAPITests)
Test adding samples (sampleA, sampleB) with no expression data to a project (from test20) ... ok
test051_POST_project (__main__.RESTAPITests)
Test adding sample (sampleC) with expression data from local path to a project (from test20) ... ok
test052_POST_project (__main__.RESTAPITests)
Test adding duplicate sample to a project and fail ... ok
test053_POST_project (__main__.RESTAPITests)
Test adding sample (sampleD) with expression data from s3 path to a project (from test20) ... ok
test054_POST_project (__main__.RESTAPITests)
Test adding sample (sampleE) with expression data and no tags from s3 path to a project (from test20) ... ok
test055_GET_project (__main__.RESTAPITests)
Test getting a project that has 5 samples (from test20, test50, test51, test54) ... ok
test056_POST_project (__main__.RESTAPITests)
Test adding sample (sampleF) with invalid expression data s3 path to a project (from test20) and fail with no sample added ... ok
test070_GET_sample (__main__.RESTAPITests)
Test getting a specific sample ... ok
test090_PUT_sample (__main__.RESTAPITests)
Test adding/updating tags on an existing sample ... ok
test100_POST_sample (__main__.RESTAPITests)
Test load cells & expression data for an existing sample (sampleA) from local path (from test50) ... ok
test101_POST_sample (__main__.RESTAPITests)
Test load cells & expression data for an existing sample (sampleB) from s3 path (from test50) ... ok
test110_GET_cell (__main__.RESTAPITests)
Test getting cells from a specific sample ... ok
test120_PUT_cell (__main__.RESTAPITests)
Test updating/adding tags on a cell or cells ... FAIL

======================================================================
FAIL: test120_PUT_cell (__main__.RESTAPITests)
Test updating/adding tags on a cell or cells
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/REST_API_Tests.py", line 629, in test120_PUT_cell
    self.fail("not yet implemented")
AssertionError: not yet implemented

----------------------------------------------------------------------
Ran 22 tests in 546.344s

FAILED (failures=1)
```

**Comment by ksens** [comment]
@mmccorry 

Reviewed and deleted branch for this PR. Only feedback is recorded at https://github.com/Paradigm4/revealgenomics-apps/issues/88

**Pull request merged**
