### PR TITLE
Rest server refactor melanie

### PR DESCRIPTION
**Pull request by mmccorry**
Creating as placeholder PR for now -- some additions needed as well as better testing.

These commits wrap most calls in the REST server using a `revealgenomics` connection object in reconnect loops.
1. Attempt the query
2. If an error thrown
  2.1 Try to re-establish a connection with SciDB
  2.2 If successful, re-attempt (1); wait and re-attempt (2.1.)

Current implementation doesn't check to make sure error thrown at (2) is due to a connection drop.

Also, need to use `revealsc_connect()` instead of `rg_connect2()` but some issues need to be worked out there.

Testing with the reconnects might best be done by running queries, halting and resuming SciDB, and making sure a reconnect happens.  This needs to be done for each endpoint.

### CODE REVIEW

**Comment by mmccorry** [comment]
@ksens 
Having some issues when performing the actual reconnect due to scoping and having both a con_read and con_write connection.  I can add more work-around logic, but it starts to get less clean again.

Here is an example of a `revealsc` function that uses both: https://github.com/Paradigm4/revealgenomics-apps/blob/master/revealsc/R/sc_registration_functions.R#L2

Do we need to have separate read and write connections, even if the read/write operations are executed in serial order?  The only advantage that pops into mind relates to permissions separation, but that could be handled at the scidb user/role level.  Also, the `revealsc_connect()` function creates (and caches) a single connection object.

**Comment by mmccorry** [comment]
@ksens 

I have made a number of new commits to this branch to fix bugs encountered when testing on our dev machine while stopping and restarting SciDB.

- Load/write queries are no longer in a reconnect loop - we first check the connection (reconnect if needed) before calling a load query with `revealsc`.
  - We will need to wrap these in a tryCatch() that makes the load queries atomic as we discussed
- Some additional errors related to connection problems are now handled.
- Only a single connection object is now used for read and load queries

This needs some further testing at a customer deployment (when we can interrupt SciDB), but the unit tests at this deployment pass in its current state and with SciDB online.

**Comment by ksens** [comment]
@mmccorry 

My only major comment is below:

## Workflow for data update endpoints: PUT / POST 

Here is the current workflow that you used the following logic for certain data update endpoints  (I am reviewing for example `POST /api/v0/project/<projectid>` -- maybe you used it only here) 

- First, call any data download API / iquery calls using `perform_revealsc_query()`
- Then, test connection using `test_and_reconnect(...)` before running the `revealgenomics` data update queries like `update_entity(...)`, `register_project()`
- Again, if required, call any data download API / iquery calls using `perform_revealsc_query()`
- Then, test connection using `test_and_reconnect(...)` before running the `revealgenomics` data update queries

I would propose the following workflow
- Test connection once before the first data update call used in that endpoint
- After that, call the regular API / iquery calls independent of whether they are data download / data update calls

My proposal has the following advantage:
- Connection is only tested once at the beginning. Saves the time (20 ms -- know this is irrelevant in terms of the overall data update time but FWIW).
- Code change is even lesser in this case. It will also make wrapping the entire data update block into one try-catch statement that does not include any reconnect logic within it.

**Note**: Your code does not need changes in data update endpoints like `@put /api/v0/project/<projectid>/sample/<sampleid>` where there is only one data update call. This seems to be the majority case.

**Comment by ksens** [comment]
Just FYI, this is my log from testing this branch on dev machine:

### Restarting scidb

```
hostname was not provided. Connecting to localhost 
Starting server to listen on port 9002
Running the swagger UI at http://127.0.0.1:9002/__swagger__/
Should not hit this condition 1 on a server where all projects created using REST API -- proceeding nevertheless
Getting all project info...: 0.974 sec elapsed
Getting project by id...: 1.772 sec elapsed
Error in SciDB connection: Error: HTTP error 502
SystemException in file: src/network/BaseConnection.h function: receive line: 171
Error id: scidb::SCIDB_SE_NETWORK::SCIDB_LE_CANT_SEND_RECEIVE
Error description: Network error. Cannot receive network message: Read failed: End of file (asio.misc:2).  An instance may be offline..

Warning in rm(con) : object 'con' not found
Trying to reconnect to SciDB... 
hostname was not provided. Connecting to localhost 
Getting project by id...: 1.815 sec elapsed
Should not hit this condition 1 on a server where all projects created using REST API -- proceeding nevertheless
Getting all project info...: 0.801 sec elapsed
```

### Restarting shim

```
Getting all project info...: 0.801 sec elapsed
Error in SciDB connection: Error: HTTP error 404
Session not found

Warning in rm(con) : object 'con' not found
Trying to reconnect to SciDB... 
hostname was not provided. Connecting to localhost 
Should not hit this condition 1 on a server where all projects created using REST API -- proceeding nevertheless
Getting all project info...: 1.585 sec elapsed
```

This appears to work as expected -- we have a self-aware REST API. Awesome stuff!

**Comment by ksens** [comment]
Tested by @mmccorry at deployment B / revealgenomics. Merging PR.

**Comment by ksens** [comment]
@mmccorry 

From slack, here is our plan for testing this PR deployment at deployment B:

1. i’ll merge in both the pending PR-s into master on revealgenomics-apps
2. i’ll install revealgenomics master on the machine
3. run the REST API update script
4. then i’ll run the Python tests (no restarts)
5. then i’ll run the R tests (no restarts)
6. then i’ll run a few tests with scidb restarts (all with the new deployment in place)

Done all but 5 at the server. Gotta run out now. 

### Python tests results

```
bash run_tests.sh -v
Connecting to REST API server at: ....
test010_GET_projects (__main__.RESTAPITests)
Test getting a list of all projects ... ok
test015_POST_project (__main__.RESTAPITests)
Test creating a project with no samples or tags ... ok
test017_POST_project (__main__.RESTAPITests)
Test creating a project with no samples and 1 tag ... ok
test020_POST_project (__main__.RESTAPITests)
Test creating a project with no samples and multiple tags ... ok
test025_GET_project (__main__.RESTAPITests)
Test retrieving a specific project that does NOT exist ... ok
test030_GET_project (__main__.RESTAPITests)
Test retrieving a specific project that should exist (from test20) ... ok
test040_PUT_project (__main__.RESTAPITests)
Test putting (updating) a project's tags ... ok
test045_POST_project (__main__.RESTAPITests)
Test adding samples to project and fail due to missing required fields ... ok
test050_POST_project (__main__.RESTAPITests)
Test adding samples (sampleA, sampleB) with no expression data to a project (from test20) ... ok
test051_POST_project (__main__.RESTAPITests)
Test adding sample (sampleC) with expression data from local path to a project (from test20) ... ok
test052_POST_project (__main__.RESTAPITests)
Test adding duplicate sample to a project and fail ... ok
test053_POST_project (__main__.RESTAPITests)
Test adding sample (sampleD) with expression data from s3 path to a project (from test20) ... ok
test054_POST_project (__main__.RESTAPITests)
Test adding sample (sampleE) with expression data and no tags from s3 path to a project (from test20) ... ok
test055_GET_project (__main__.RESTAPITests)
Test getting a project that has 5 samples (from test20, test50, test51, test54) ... ok
test070_GET_sample (__main__.RESTAPITests)
Test getting a specific sample ... ok
test090_PUT_sample (__main__.RESTAPITests)
Test adding/updating tags on an existing sample ... ok
test100_POST_sample (__main__.RESTAPITests)
Test load cells & expression data for an existing sample (sampleA) from local path (from test50) ... ok
test101_POST_sample (__main__.RESTAPITests)
Test load cells & expression data for an existing sample (sampleB) from s3 path (from test50) ... ok
test110_GET_cell (__main__.RESTAPITests)
Test getting cells from a specific sample ... ok
test120_PUT_cell (__main__.RESTAPITests)
Test updating/adding tags on a cell or cells ... FAIL

======================================================================
FAIL: test120_PUT_cell (__main__.RESTAPITests)
Test updating/adding tags on a cell or cells
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/REST_API_Tests.py", line 566, in test120_PUT_cell
    self.fail("not yet implemented")
AssertionError: not yet implemented

----------------------------------------------------------------------
Ran 20 tests in 443.667s

FAILED (failures=1)
```

**Comment by ksens** [comment]
Last remaining item (R tests) also completed and passed:

```R
.1....23.....4..........5..
══ Failed ══════════════════════════════════════════════════════════════════════
── 1. Failure: test010_GET_projects - Test getting a list of all projects (@test
identical(rest_projects, reveal_projects) isn't true.

── 2. Failure: test025_GET_project - Test retrieving a specific project that doe
identical(rest_project, reveal_project) isn't true.

── 3. Failure: test030_GET_project - Test retrieving a specific project that sho
identical(rest_project, reveal_project) isn't true.

── 4. Failure: test035_GET_project - Test retrieving a specific project that sho
identical(rest_project, reveal_project) isn't true.

── 5. Failure: test070_GET_sample - Test getting a specific sample (@test_reveal
`rest_sample` not equal to `reveal_sample`.
Component “tags_df”: Component “doid”: 'current' is not a factor
Component “tags_df”: Component “enrichment”: 'current' is not a factor
Component “tags_df”: Component “organism”: 'current' is not a factor
Component “tags_df”: Component “uberonid”: 'current' is not a factor
```

Only failing tests are equivalency ones (expected to fail).

**Pull request merged**
